services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    expose:
      - 6379
    networks:
      - livekit-network # Adicionado
  livekit:
    image: livekit/livekit-server
    command: --dev --redis-host redis:6379 # Alterado para usar o nome do serviço Redis
    ports:
      - "7880:7880"
      - "7881:7881"
      - "7882:7882/udp"
    networks:
      - livekit-network # Adicionado
  sip:
    image: livekit/sip
    environment:
      SIP_CONFIG_BODY: |
        log_level: debug
        api_key: ${LIVEKIT_API_KEY}
        api_secret: ${LIVEKIT_API_SECRET}
        ws_url: ${LIVEKIT_URL}
        sip:
          username: ${SIP_USERNAME}
          password: ${SIP_PASSWORD}
          server: ${SIP_SERVER}
        redis:
          address: 'redis:6379' # Alterado para usar o nome do serviço Redis
        sip_port: 5060
        rtp_port: 10000-20000
        use_external_ip: true
        logging:
          level: debug
    ports:
      - "5060:5060"
      - "10000-20000:10000-20000/udp"
    networks:
      - livekit-network # Adicionado

networks:
  livekit-network: # Rede Docker adicionada
    driver: bridge
volumes:
  redis_data:
