version: '3.8'

services:
  redis:
    image: redis
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"  # Expõe a porta do Redis para outros serviços
    restart: unless-stopped

  livekit:
    image: livekit/livekit-server
    command: --dev --redis-host redis:6379  # Usa o nome do serviço "redis"
    depends_on:
      - redis  # Garante que o Redis seja iniciado primeiro
    environment:
      LIVEKIT_API_KEY: ${LIVEKIT_API_KEY}
      LIVEKIT_API_SECRET: ${LIVEKIT_API_SECRET}
      LIVEKIT_URL: ${LIVEKIT_URL}
    restart: unless-stopped

  sip:
    image: livekit/sip
    depends_on:
      - redis  # Garante que o Redis seja iniciado primeiro
    environment:
      SIP_CONFIG_BODY: |
        log_level: debug
        api_key: ${LIVEKIT_API_KEY}
        api_secret: ${LIVEKIT_API_SECRET}
        ws_url: ${LIVEKIT_URL}
        sip:
          username: ${SIP_USERNAME}
          password: ${SIP_PASSWORD}
          server: ${SIP_SERVER}
        redis:
          address: 'redis:6379'  # Usa o nome do serviço "redis"
        sip_port: 5060
        rtp_port: 10000-20000
        use_external_ip: true
        logging:
          level: debug
    ports:
      - "5060:5060/udp"  # Expõe a porta SIP
      - "10000-20000:10000-20000/udp"  # Expõe o range de portas RTP
    restart: unless-stopped

volumes:
  redis_data:
